gpu: "0"
multi_gpu: null # "0,1,2,3"

model_name: PointConv

full: False

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/

arch: PointConv
last_relu: False
allow_less_points: False

# general args
batch_size: 1 # if down sampling ==voxel batch_size must be 1 for eval ,because multiple size will use pad in collecter
pretrain: PointConv_112_0.0533.pth
dim: 3
num_points: 18776 # 31000 # 18776

DEVICE: cuda

dataset: SemanticKitti # FlyingThings3DSubset KITTI
data_root: /share/sgb/semantic_kitti/SemanticKitti_Flow_Dataset_1_non_ground_point

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True
  DOWN_SAMPLE_METHOD: voxel # voxel # random 
  VOXEL_CHOICE: choice_one # mean # choice_one
  VOXEL_SIZE: 0.2
  PAD_METHOD: sample # zero # sample


# miscalleneous
workers: 16








